import Penyewaan from "@/pages/Crud3/Penyewaan";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Penyewaan - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default function page() {
    return <Penyewaan/>;
}