import Sewa from "@/pages/Sewa/Sewa";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sewa - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default function page() {
  return <Sewa />;
}
