import Tentang from "@/pages/Tentang/Tentang.view";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tentang - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default function page() {
  return <Tentang />;
}
