import Alat from "@/pages/Alat/Alat";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Alat - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default Alat;
