import Login from "@/pages/Login/Login";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Masuk - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default Login;
