import Login from "@/pages/SignIn/SignIn";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Daftar - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default Login;
