import PelangganData from "@/pages/Crud3/Pelanggandata";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pelanggandata - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default function page() {
    return <PelangganData/>;
}