import Kontak from "@/pages/Kontak/Kontak";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kontak - Aplikasi Sewa Alat",
  description: "Generated by create next app",
};

export default function page() {
  return <Kontak />;
}
